core:
  plans:
    app:
      type: dev
      require: SQLite3 Parsedown
    view: {path: $SELF/mvc}
    mem: {path: $SELF/mvc}
  databases:
    driver: sqlite3
    dsn: $SELF/venus.base

tw: w3/tailwind.yaml
html: w3/html.yaml